variables:
  DEBIAN_FRONTEND: noninteractive
  GRADLE_OPTIONS: --info --stacktrace --warning-mode=all
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"

default:
  cache:
    paths:
      - .gradle/caches
      - .gradle/native
      - .gradle/wrapper

# For testing with older Java versions.
# Gradle 9 requires at least Java 17 to run,
# but can still compile/test using older JDKs if requested via a toolchain configuration.
# Thus, if the Java version provided by the eclipse-temurin image in question is too old to run Gradle,
# we additionally install Ubuntu's default JRE,
# which should always be new enough to run current Gradle versions.
# For example, as of 2025-11,
# the eclipse-temurin:8 image is based on Ubuntu 24.04 LTS (noble),
# whose default Java version is Java 21.
# Jobs that extend this template must also set the environment variable ORG_GRADLE_PROJECT_javaToolchainVersion
# to the Java version number of the eclipse-temurin image.
.linux_old_java:
  variables:
    # Change JAVA_HOME to the system default Java
    # so that Gradle runs using this newer Java version.
    JAVA_HOME: "/usr/lib/jvm/default-java"
  before_script:
    - apt-get update
    - apt-get install -y default-jre-headless

test:
  extends: .linux_old_java
  stage: test
  image: eclipse-temurin:8
  variables:
    ORG_GRADLE_PROJECT_javaToolchainVersion: "8"
  script:
    - apt-get update
    - apt-get install --assume-yes git jupyter-client jupyter-console
    - ./gradlew ${GRADLE_OPTIONS} check shadowJar
    # Test installation of kernel into Jupyter.
    - java -jar build/libs/prob2-jupyter-kernel-*-all.jar install --user
    - |
      jupyter console --kernel=prob2 --simple-prompt << EOF
      :version
      EOF
  artifacts:
    expire_in: 1 week
    paths:
      - build/distributions
      - build/libs

deploy:
  stage: deploy
  only:
    - master@general/stups/prob2-jupyter-kernel
  needs:
    - test
  image: alpine:3
  before_script:
    - apk update
    - apk add lftp openssh-client
  script:
    - |
      filename="$(echo build/libs/prob2-jupyter-kernel-*-all.jar)"
      case "${filename}" in
        (*-SNAPSHOT-all.jar)
          # Don't upload SNAPSHOT builds
        ;;
        
        (*-all.jar)
          # Do upload release builds
          LFTP_PASSWORD="${DEPLOY_PASSWORD}" lftp -c "set cmd:fail-exit true; set sftp:auto-confirm true; open --user ${DEPLOY_USERNAME} --env-password sftp://${DEPLOY_HOST}/${DEPLOY_REMOTE_BASEDIR}/downloads/prob2-jupyter/; mput build/libs/prob2-jupyter-kernel-*-all.jar"
        ;;
      esac
