variables:
  DEBIAN_FRONTEND: noninteractive
  GRADLE_OPTIONS: --info --stacktrace --warning-mode=all

default:
  image: eclipse-temurin:8
  cache:
    paths:
      - .gradle/caches
      - .gradle/native
      - .gradle/wrapper
  before_script:
    - apt-get update
    - apt-get install --assume-yes git jupyter-client jupyter-console
    - export GRADLE_USER_HOME="${PWD}/.gradle"

test:
  stage: test
  script:
    - ./gradlew ${GRADLE_OPTIONS} check shadowJar
    # Test installation of kernel into Jupyter.
    - java -jar build/libs/prob2-jupyter-kernel-*-all.jar install --user
    - |
      jupyter console --kernel=prob2 --simple-prompt << EOF
      :version
      EOF
  artifacts:
    expire_in: 1 week
    paths:
      - build/distributions
      - build/libs

deploy:
  stage: deploy
  only:
    - master@general/stups/prob2-jupyter-kernel
  needs:
    - test
  image: alpine:3
  before_script:
    - apk update
    - apk add lftp openssh-client
  script:
    - |
      filename="$(echo build/libs/prob2-jupyter-kernel-*-all.jar)"
      case "${filename}" in
        (*-SNAPSHOT-all.jar)
          # Don't upload SNAPSHOT builds
        ;;
        
        (*-all.jar)
          # Do upload release builds
          LFTP_PASSWORD="${DEPLOY_PASSWORD}" lftp -c "set cmd:fail-exit true; set sftp:auto-confirm true; open --user ${DEPLOY_USERNAME} --env-password sftp://${DEPLOY_HOST}/${DEPLOY_REMOTE_BASEDIR}/downloads/prob2-jupyter/; mput build/libs/prob2-jupyter-kernel-*-all.jar"
        ;;
      esac
